# Generated by Django 6.0.7 on 2026-07-19 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='orginal_url',
            new_name='original_url',
        ),
    ]
